import { SPECTRUM_NAMES, SPECTRUM_LABELS } from '../data/weights.js';
import { archetypes } from '../data/archetypes.js';

/**
 * Describe where a score falls on its spectrum in plain English.
 */
function describeScore(spectrumId, score) {
  const [leftLabel, rightLabel] = SPECTRUM_LABELS[spectrumId];

  if (score <= 20) return `Strongly ${leftLabel.toLowerCase()}`;
  if (score <= 35) return `Lean ${leftLabel.toLowerCase()}`;
  if (score <= 65) return `Balanced`;
  if (score <= 80) return `Lean ${rightLabel.toLowerCase()}`;
  return `Strongly ${rightLabel.toLowerCase()}`;
}

/**
 * Generate a preference description for a spectrum.
 */
function spectrumLine(spectrumId, score) {
  const name = SPECTRUM_NAMES[spectrumId];
  const [leftLabel, rightLabel] = SPECTRUM_LABELS[spectrumId];
  const position = describeScore(spectrumId, score);
  return `- ${name}: ${position} (${leftLabel} ↔ ${rightLabel}, score: ${Math.round(score)}/100)`;
}

/**
 * Generate a plain-text AI context block optimized for pasting into
 * ChatGPT, Claude, or any LLM chat to personalize responses.
 *
 * @param {Object} opts
 * @param {string} opts.displayName - User's display name
 * @param {Object} opts.normalizedScores - Spectrum scores keyed by ID (1-14)
 * @param {Object} opts.archetypeResult - { primary, secondary, primaryName, secondaryName }
 * @returns {string} Plain-text context block
 */
export function generateAIContext({ displayName, normalizedScores, archetypeResult }) {
  if (!normalizedScores || !archetypeResult) return '';

  const primary = archetypes[archetypeResult.primary];
  const secondary = archetypeResult.secondary ? archetypes[archetypeResult.secondary] : null;

  // Split spectrums into strengths (strong preference) and balanced
  const strongPrefs = [];
  const leanPrefs = [];
  const balanced = [];

  for (let id = 1; id <= 14; id++) {
    const score = normalizedScores[id];
    if (score == null) continue;
    if (score <= 20 || score >= 80) strongPrefs.push(id);
    else if (score <= 35 || score >= 65) leanPrefs.push(id);
    else balanced.push(id);
  }

  const lines = [];

  // Header
  lines.push('## About Me — AI Interaction Profile');
  lines.push('');
  lines.push(`I am "${primary?.name || archetypeResult.primaryName}"${secondary ? ` with "${secondary.name || archetypeResult.secondaryName}" secondary` : ''}.`);
  lines.push('');

  // Archetype description
  if (primary?.summary) {
    lines.push(primary.summary);
    lines.push('');
  }

  // All spectrum preferences
  lines.push('### My Preferences');
  lines.push('');
  for (let id = 1; id <= 14; id++) {
    const score = normalizedScores[id];
    if (score == null) continue;
    lines.push(spectrumLine(id, score));
  }
  lines.push('');

  // What works well — strong preferences
  if (strongPrefs.length > 0) {
    lines.push('### What Works Well For Me');
    lines.push('');
    for (const id of strongPrefs) {
      const score = normalizedScores[id];
      const [leftLabel, rightLabel] = SPECTRUM_LABELS[id];
      const name = SPECTRUM_NAMES[id];
      if (score <= 20) {
        lines.push(`- ${name}: I strongly prefer ${leftLabel.toLowerCase()} over ${rightLabel.toLowerCase()}.`);
      } else {
        lines.push(`- ${name}: I strongly prefer ${rightLabel.toLowerCase()} over ${leftLabel.toLowerCase()}.`);
      }
    }
    lines.push('');
  }

  // Where I need support — mid-range or areas to be aware of
  if (leanPrefs.length > 0) {
    lines.push('### Moderate Preferences');
    lines.push('');
    for (const id of leanPrefs) {
      const score = normalizedScores[id];
      const [leftLabel, rightLabel] = SPECTRUM_LABELS[id];
      const name = SPECTRUM_NAMES[id];
      if (score <= 35) {
        lines.push(`- ${name}: I lean toward ${leftLabel.toLowerCase()} but can adapt when needed.`);
      } else {
        lines.push(`- ${name}: I lean toward ${rightLabel.toLowerCase()} but can adapt when needed.`);
      }
    }
    lines.push('');
  }

  // How to work with me
  lines.push('### How to Work With Me');
  lines.push('');
  lines.push(buildWorkingGuidelines(normalizedScores));
  lines.push('');

  // Footer
  lines.push(`Generated by AI Onboard for ${displayName} on ${new Date().toLocaleDateString()}.`);

  return lines.join('\n');
}

/**
 * Build concise working guidelines from scores.
 */
function buildWorkingGuidelines(scores) {
  const tips = [];

  // Communication density
  if (scores[1] != null) {
    if (scores[1] <= 30) tips.push('Keep responses concise and to the point. Skip preamble and filler.');
    else if (scores[1] >= 70) tips.push('Provide thorough, detailed responses. I appreciate depth and context.');
  }

  // Communication tone
  if (scores[2] != null) {
    if (scores[2] <= 30) tips.push('Be direct and straightforward. Skip pleasantries when possible.');
    else if (scores[2] >= 70) tips.push('Use a warm, conversational tone. I value the human side of interaction.');
  }

  // Learning mode
  if (scores[3] != null) {
    if (scores[3] <= 30) tips.push('Give me structured, step-by-step approaches.');
    else if (scores[3] >= 70) tips.push('Let me explore freely. Suggest tangents and connections rather than rigid steps.');
  }

  // Problem-solving
  if (scores[4] != null) {
    if (scores[4] <= 30) tips.push('Lead with data, analysis, and logical reasoning.');
    else if (scores[4] >= 70) tips.push('Support creative, intuitive problem-solving. Help me brainstorm before narrowing down.');
  }

  // Feedback style
  if (scores[5] != null) {
    if (scores[5] <= 30) tips.push('Give me direct, unvarnished feedback. Don\'t soften bad news.');
    else if (scores[5] >= 70) tips.push('Frame feedback constructively. Guide me toward improvements rather than pointing out flaws.');
  }

  // Decision autonomy
  if (scores[6] != null) {
    if (scores[6] <= 30) tips.push('Let me make decisions independently. Provide options without pushing a recommendation.');
    else if (scores[6] >= 70) tips.push('Proactively suggest what you think is best. I value your recommendations.');
  }

  // AI autonomy
  if (scores[11] != null) {
    if (scores[11] <= 30) tips.push('Let me stay in control. Ask before taking initiative or making assumptions.');
    else if (scores[11] >= 70) tips.push('Take initiative and fill in gaps. I trust you to run with things.');
  }

  // Collaboration style
  if (scores[14] != null) {
    if (scores[14] <= 30) tips.push('I work best when I execute independently. Give me what I need and step back.');
    else if (scores[14] >= 70) tips.push('Engage as an active thinking partner. Build on my ideas and offer your own.');
  }

  return tips.join('\n');
}
