import ActionBar from './ActionBar.jsx';
import ArchetypeCard from './ArchetypeCard.jsx';
import SpectrumChart from './SpectrumChart.jsx';

export default function ProfileView({ profile, scores, zones, archetype, onRetake, onShare, isSharedView }) {
  if (!profile) return null;

  // Normalize instructions to { text, core } objects (handles both old string[] and new object[] formats)
  const instructions = (profile.instructions || []).map(i =>
    typeof i === 'string' ? { text: i, core: false } : i
  );
  const coreInstructions = instructions.filter(i => i.core);
  const standardInstructions = instructions.filter(i => !i.core);

  return (
    <div className="w-full max-w-[720px] mx-auto pb-24 px-4 sm:px-0">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-2xl sm:text-3xl font-semibold mb-2" style={{ fontFamily: 'var(--font-heading)', color: 'var(--color-text-primary)' }}>
          {isSharedView ? 'AI Profile' : 'Your AI Profile'}
        </h1>
        <p className="text-sm" style={{ color: 'var(--color-text-secondary)' }}>
          Generated by AI Onboard · {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>
      </div>

      {/* Archetype Card */}
      {archetype && (
        <div className="mb-10">
          <ArchetypeCard archetype={archetype} />
        </div>
      )}

      {/* About Me */}
      <ProfileSection title="About Me">
        {profile.aboutMe.map((paragraph, idx) => (
          <p key={idx} className="text-[15px] sm:text-base leading-relaxed mb-4 last:mb-0" style={{ color: 'var(--color-text-primary)' }}>
            {paragraph}
          </p>
        ))}
      </ProfileSection>

      {/* Spectrum Chart */}
      {scores && zones && (
        <ProfileSection title="Your Spectrum">
          <SpectrumChart scores={scores} zones={zones} />
        </ProfileSection>
      )}

      {/* Work Context */}
      <ProfileSection title="Work Context">
        <p className="text-[15px] sm:text-base leading-relaxed" style={{ color: 'var(--color-text-primary)' }}>
          {profile.workContext}
        </p>
      </ProfileSection>

      {/* Custom Notes (before instructions — highest-signal user-written content) */}
      {profile.customNotes && (
        <ProfileSection title="In My Own Words">
          <div
            className="px-4 py-3 rounded text-[14px] sm:text-[15px] leading-relaxed italic"
            style={{
              backgroundColor: 'var(--color-surface)',
              color: 'var(--color-text-primary)',
              borderLeft: '2px solid var(--color-accent)'
            }}
          >
            {profile.customNotes}
          </div>
        </ProfileSection>
      )}

      {/* How to Work With Me */}
      <ProfileSection title="How to Work With Me">
        <div className="flex flex-col gap-3">
          {coreInstructions.map((instruction, idx) => (
            <div
              key={`core-${idx}`}
              className="pl-4 py-1 text-[14px] sm:text-[15px] leading-relaxed font-medium"
              style={{
                borderLeft: '3px solid var(--color-accent)',
                color: 'var(--color-text-primary)'
              }}
            >
              {instruction.text}
            </div>
          ))}
          {standardInstructions.map((instruction, idx) => (
            <div
              key={`std-${idx}`}
              className="pl-4 py-1 text-[14px] sm:text-[15px] leading-relaxed"
              style={{
                borderLeft: '2px solid var(--color-border)',
                color: 'var(--color-text-primary)'
              }}
            >
              {instruction.text}
            </div>
          ))}
        </div>
      </ProfileSection>

      {/* Getting Better Results (visible but excluded from copy) */}
      <ProfileSection title="Getting Better Results">
        <p className="text-sm mb-4" style={{ color: 'var(--color-text-secondary)' }}>
          Tips for getting the most out of your AI conversations:
        </p>
        <div className="flex flex-col gap-4">
          {profile.tips.map((tip, idx) => (
            <div key={idx} className="text-[14px] sm:text-[15px] leading-relaxed">
              <span className="font-medium" style={{ color: 'var(--color-text-primary)' }}>{tip.bold}</span>{' '}
              <span style={{ color: 'var(--color-text-secondary)' }}>{tip.text}</span>
            </div>
          ))}
        </div>
      </ProfileSection>

      <ActionBar
        markdown={profile.markdownForCopy}
        onRetake={onRetake}
        onShare={onShare}
        isSharedView={isSharedView}
      />
    </div>
  );
}

function ProfileSection({ title, children }) {
  return (
    <div className="mb-10">
      <div className="mb-4 pt-6" style={{ borderTop: '1px solid var(--color-border)' }}>
        <h2
          className="text-xs font-semibold tracking-widest uppercase"
          style={{ color: 'var(--color-accent)' }}
        >
          {title}
        </h2>
      </div>
      {children}
    </div>
  );
}
