import ActionBar from './ActionBar.jsx';

export default function ProfileView({ profile, onRetake }) {
  if (!profile) return null;

  return (
    <div className="w-full max-w-[720px] mx-auto pb-24">
      {/* Header */}
      <div className="mb-12">
        <h1 className="text-3xl font-semibold mb-2" style={{ fontFamily: 'var(--font-heading)', color: 'var(--color-text-primary)' }}>
          Your AI Profile
        </h1>
        <p className="text-sm" style={{ color: 'var(--color-text-secondary)' }}>
          Generated by AI Onboard · {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>
      </div>

      {/* About Me */}
      <ProfileSection title="About Me">
        {profile.aboutMe.map((paragraph, idx) => (
          <p key={idx} className="text-base leading-relaxed mb-4 last:mb-0" style={{ color: 'var(--color-text-primary)' }}>
            {paragraph}
          </p>
        ))}
      </ProfileSection>

      {/* Work Context */}
      <ProfileSection title="Work Context">
        <p className="text-base leading-relaxed" style={{ color: 'var(--color-text-primary)' }}>
          {profile.workContext}
        </p>
      </ProfileSection>

      {/* How to Work With Me */}
      <ProfileSection title="How to Work With Me">
        <div className="flex flex-col gap-3">
          {profile.instructions.map((instruction, idx) => (
            <div
              key={idx}
              className="pl-4 py-1 text-[15px] leading-relaxed"
              style={{
                borderLeft: '2px solid var(--color-accent)',
                color: 'var(--color-text-primary)'
              }}
            >
              {instruction}
            </div>
          ))}
        </div>
      </ProfileSection>

      {/* Getting Better Results */}
      <ProfileSection title="Getting Better Results">
        <p className="text-sm mb-4" style={{ color: 'var(--color-text-secondary)' }}>
          Here are some tips for getting the most out of your AI conversations:
        </p>
        <div className="flex flex-col gap-4">
          {profile.tips.map((tip, idx) => (
            <div key={idx} className="text-[15px] leading-relaxed">
              <span className="font-medium" style={{ color: 'var(--color-text-primary)' }}>{tip.bold}</span>{' '}
              <span style={{ color: 'var(--color-text-secondary)' }}>{tip.text}</span>
            </div>
          ))}
        </div>
      </ProfileSection>

      {/* Custom Notes */}
      {profile.customNotes && (
        <ProfileSection title="Custom Notes">
          <div
            className="px-4 py-3 rounded text-[15px] leading-relaxed italic"
            style={{
              backgroundColor: 'var(--color-surface)',
              color: 'var(--color-text-primary)',
              borderLeft: '2px solid var(--color-border)'
            }}
          >
            {profile.customNotes}
          </div>
        </ProfileSection>
      )}

      <ActionBar markdown={profile.markdown} onRetake={onRetake} />
    </div>
  );
}

function ProfileSection({ title, children }) {
  return (
    <div className="mb-10">
      <div className="mb-4 pt-6" style={{ borderTop: '1px solid var(--color-border)' }}>
        <h2
          className="text-xs font-semibold tracking-widest uppercase"
          style={{ color: 'var(--color-accent)' }}
        >
          {title}
        </h2>
      </div>
      {children}
    </div>
  );
}
